name: provider_test
description: A testing library which makes it easy to test providers. Built after bloc_test package.
version: 2.0.2

repository: https://github.com/EmanuelBalaban/provider_test
issue_tracker: https://github.com/EmanuelBalaban/provider_test/issues
# homepage: https://github.com/
# documentation: https://github.com/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # Collections and utilities functions and classes related to collections.
  collection: ^1.17.1

  # Annotations used to express developer intentions that can't otherwise be deduced by statically
  # analyzing source code.
  meta: ^1.9.1

  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.24.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Software analytics tool that helps developers analyse and improve software quality.
  dart_code_metrics: ^5.7.4

  # Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
  flutter_lints: ^2.0.1

  # Support for specifying test expectations via an extensible Matcher class. Also includes a number
  # of built-in Matcher implementations for common cases.
  matcher: ^0.12.16

  # The user facing API for structuring Dart tests and checking expectations.
  test_api: ^0.5.2

  # Lint rules for Dart and Flutter used internally at Very Good Ventures.
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  test_api: 0.5.2
  matcher: ^0.12.16

import_sorter:
  comments: false